---
- name: Install Kindle via Mac App Store
  command: mas install "{{ item.id }}"
  args:
    creates: /Applications/{{ item.name }}.app
  with_items:
    - { id: 405399194, name: "Kindle" }
  when: ansible_os_family == "Darwin" and prefer_mas_over_homebrew == true

- name: Install Kindle via Homebrew
  homebrew_cask:
    name: kindle
  when: ansible_os_family == "Darwin" and prefer_mas_over_homebrew == false
